default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  username: postgres
  timeout: 5000

development:
  <<: *default
  database: performance_workshop_development

test:
  <<: *default
  database: performance_workshop_test

production:
  url: <%= ENV['DATABASE_URL'] %>
